import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/Header";
import Footer from "./_components/footer/Footer";
import RecoilRootWrapper from "./_recoil/RecoilRootWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="min-h-screen">
          <RecoilRootWrapper>{children}</RecoilRootWrapper>
        </main>
        <Footer />
      </body>
    </html>
  );
}
